### ISSUE TITLE
Event Deletion by Admin

### ISSUE THREAD

**Issue by DoctorSoup143** [DoctorSoup143/KTN-Dev#60]
Admins should be able to delete any events in the future. Currently event deletion errors out.

**Comment by mphacker** [comment]
Events have a lot of related data including registrations and scoring.  If we allow the deletion of an event that has related data, we will have to delete all of the related data too.   Another option is to instead flag an item as "deleted" so it doesn't show in the UI but it stays in the database.

Currently you will get an error because we haven't decided how we want to handle deletions.   What is the direction you think we should go?  @DoctorSoup143

**Comment by mphacker** [comment]
Resolved with issue #72
